# Generated by Django 2.1.5 on 2019-02-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_adminlte', '0003_auto_20190204_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_io',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('csv', models.FileField(upload_to='media/csv/')),
            ],
        ),
    ]
